apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $METAL_NAMESPACE
  name: config
data:
  config: |
    address-pools:
    - name: $DEFAULT_NETWORK/$DEFAULT_NETMASK
      protocol: layer2
      addresses:
      - $METAL_START_IP-$METAL_END_IP
