#!/bin/bash -E
# Must be run as sudo
[ `whoami` = root ] || { sudo -E "$0" "$@"; exit $?; }
# Change to the current directory
directory="$(dirname "${BASH_SOURCE[0]}")"
cd $directory
source $directory/scripts/utils
import_vars $directory/env
export BASE_IP=$(echo $DEFAULT_NETWORK |cut -d"." -f1-3)
# Install common packages 
case $(get_distro) in 
  centos|fedora)
    sudo yum update -y
    sudo yum install -y ca-certificates curl software-properties-common apache2-utils jq unzip rename postgresql vim sshpass snapd wget nc
    # symlink snap
    sudo ln -s /var/lib/snapd/snap /snap
    sudo systemctl restart snapd
    # CentOS version of git is way out of date 
    yum install -y \
    https://repo.ius.io/ius-release-el7.rpm \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum remove -y git
    yum install -y git236
    ;;
  rhel)
    sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    sudo dnf update -y 
    sudo yum install -y ca-certificates curl software-properties-common apache2-utils jq unzip rename postgresql vim sshpass snapd wget nc
    # enable snap
    sudo systemctl enable --now snapd.socket
    # symlink snap
    sudo ln -s /var/lib/snapd/snap /snap
    sudo systemctl restart snapd
    ;;
  ubuntu|debian)
    apt update
    apt install apt-transport-https ca-certificates curl software-properties-common \
    apache2-utils jq unzip rename python postgresql-client vim sshpass snapd  wget -y
    ;;
  darwin)
    echo "MacOS is not supported by this script"
    exit;
esac

# Install terraform from utils script
install_terraform
# install ansible from utils script
install_ansible
# Install kubectl
install_kubectl
echo "source <(kubectl completion $(get_shell))" >> ~/.$(get_shell)rc
# Install Helm
install_helm
# Add kubectl and helm bash completion
echo "source <(kubectl completion $(get_shell))" >> ~/.$(get_shell)rc
echo "source <(helm completion $(get_shell)" >> ~/.$(get_shell)rc


# Install retry script
sudo sh -c "curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && chmod +x /usr/local/bin/retry"

# Install cfssl
curl -sLo /usr/local/bin/cfssl https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_linux_amd64
curl -sLo /usr/local/bin/cfssljson https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssljson_1.5.0_linux_amd64
chmod +x /usr/local/bin/cfssl*

# Install Powershell and PowerCLI (vcenter, steamfitter)
snap install powershell --classic


# Replace variables in files
#replace_vars $directory/common '.*\.(json|conf|yaml|yml)'
#replace_vars $directory/crucible '.*\.(json|conf|yaml|yml|sql)'
replace_vars $directory/k3s-ansible '.*\.(json|conf|yaml|yml)'
replace_vars $directory/terraform '.*\.(json|conf|yaml|yml|auto.tfvars)'
replace_vars $directory/values '.*\.(json|conf|yaml|yml)'
# replace_vars $directory/crucible/setup-gitlab
# chmod +x $directory/crucible/setup-gitlab
# replace_vars $directory/scripts/identity-seed.example.sh
# chmod +x $directory/scripts/identity-seed.example.sh
# replace_vars $directory/crucible/import-content
# chmod +x $directory/crucible/import-content
echo "Finished Prep."
