#!/bin/bash -xe
# Must be run as sudo
[ `whoami` = root ] || { sudo "$0" "$@"; exit $?; }
# Change to the current directory
directory="$(dirname "${BASH_SOURCE[0]}")"
cd $directory
source $directory/scripts/utils
import_vars $directory/env
export BASE_IP=$(echo $DEFAULT_NETWORK |cut -d"." -f1-3)
# Install common packages 
apt update
apt install apt-transport-https ca-certificates curl software-properties-common \
apache2-utils jq unzip rename python postgresql-client vim -y
# Install terraform from utils script
install_terraform
# install ansible from utils script
install_ansible
# Install Helm
install_helm
# Replace variables in files
replace_vars $directory/common '.*\.(json|conf|yaml|yml)'
replace_vars $directory/crucible '.*\.(json|conf|yaml|yml|sql)'
replace_vars $directory/k3s-ansible '.*\.(json|conf|yaml|yml)'
replace_vars $directory/terraform '.*\.(json|conf|yaml|yml|auto.tfvars)'
replace_vars $directory/values '.*\.(json|conf|yaml|yml)'
replace_vars $directory/crucible/setup-gitlab
chmod +x $directory/crucible/setup-gitlab
replace_vars $directory/scripts/identity-seed.example.sh
chmod +x $directory/scripts/identity-seed.example.sh
replace_vars $directory/crucible/import-content
chmod +x $directory/crucible/import-content
echo "Finished Prep."
