#!/bin/bash -xe
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

#############################
#   Foundry Stack Install   #
#############################

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"

# Forward coredns to host dnsmasq
kubectl get configmap/coredns -n kube-system -o yaml | sed "s/\/etc\/resolv.conf/$DNS_01/" | kubectl replace -f -
kubectl rollout restart deployment/coredns -n kube-system

# Disable HSTS
# kubectl patch configmap $INGRESS_CONFIGMAP \
#                         --patch "$(cat ingress-hsts-disable.yaml)" \
#                         --namespace $INGRESS_NAMESPACE

# Add host certificate
kubectl create secret tls appliance-cert --key certs/host-key.pem --cert <( cat certs/host.pem certs/int-ca.pem ) --dry-run=client -o yaml | kubectl apply -f -
# Add root ca
kubectl create secret generic appliance-root-ca --from-file=appliance-root-ca=certs/root-ca.pem --dry-run=client -o yaml | kubectl apply -f -
kubectl create configmap appliance-root-ca --from-file=root-ca.crt=certs/root-ca.pem --from-file=vsphere-ca.crt=certs/vsphere.pem --dry-run=client -o yaml | kubectl apply -f -
# Install PostgreSQL and pgAdmin4
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add runix https://helm.runix.net/
helm upgrade --wait --install -f postgresql.values.yaml postgresql bitnami/postgresql --version 9.8.11
#helm install -f pgadmin4.values.yaml pgadmin4 runix/pgadmin4

# Install code-server (browser-based VS Code)
helm repo add nicholaswilde https://nicholaswilde.github.io/helm-charts/
helm upgrade --wait --install -f code-server.values.yaml code-server nicholaswilde/code-server

# Kubernetes Dashboard
# helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
# helm upgrade --install -f kubernetes-dashboard.values.yaml kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard
# Add root CA to chart values
# ed -s staticweb.values.yaml <<< $'/cacert:/s/\"\"/|-/\n/cacert:/r !sed "s/^/  /" certs/root-ca.pem\nw'

# cp certs/root-ca.pem web/root-ca.crt

# Install NFS server
helm repo add kvaps https://kvaps.github.io/charts
helm upgrade --wait --install -f nfs-server-provisioner.values.yaml nfs-server-provisioner kvaps/nfs-server-provisioner
kubectl patch $INGRESS_KIND $INGRESS_CONTROLLER_NAME -n $INGRESS_NAMESPACE --type 'json' --patch \
  '[{"op": "add", "path": "/spec/template/spec/containers/0/ports/-", "value": {"name":"nfs-tcp","hostPort":2049,"containerPort":2049,"protocol":"TCP"}}]' || true
kubectl patch $INGRESS_KIND $INGRESS_CONTROLLER_NAME -n $INGRESS_NAMESPACE --type 'json' --patch \
  '[{"op": "add", "path": "/spec/template/spec/containers/0/ports/-", "value": {"name":"nfs-udp","hostPort":2049,"containerPort":2049,"protocol":"UDP"}}]' || true
kubectl apply -f nfs-ingress.yaml --dry-run=client -o yaml | kubectl apply -f -

# Install Gitea
# helm repo add gitea https://dl.gitea.io/charts/
# helm upgrade --install -f gitea.values.yaml gitea gitea/gitea
# timeout 5m bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://$DOMAIN/gitea)" != "200" ]]; do sleep 5; done' || false
# ./setup-gitea

# Install Common foundry apps
helm repo add sei https://helm.cyberforce.site/charts
helm upgrade --wait --install -f identity.values.yaml identity ../charts/identity
# replacing environment variables clobbers the seed.sh script so we need to update it
kubectl create configmap identity-identity-api --from-file=seed.sh=../scripts/identity-seed.example.sh -o yaml --dry-run=client | kubectl apply -f -
# helm upgrade --install -f staticweb.values.yaml staticweb sei/staticweb