#!/bin/bash -xe
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.
MKDOCS_DIR=~/k3s-production/mkdocs
CURL_OPTS=( --silent --header "accept: application/json" --header "Content-Type: application/json" )
REQ=$( curl_proxy "${CURL_OPTS[@]}" \
                --user administrator:$ADMIN_PASS \
                --request DELETE "https://$DOMAIN/gitea/api/v1/users/administrator/tokens/appliance-setup"
)
USER_TOKEN=$( curl_proxy "${CURL_OPTS[@]}" \
                --user administrator:$ADMIN_PASS \
                --request POST "https://$DOMAIN/gitea/api/v1/users/administrator/tokens" \
                --data "{ \"name\": \"appliance-setup\"}" | jq -r '.sha1'
)

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"

# Set git user vars
git config --global user.name "Administrator"
git config --global user.email "administrator@$DOMAIN"

# Create foundry-docs organization
curl_proxy "${CURL_OPTS[@]}" \
  --request POST "https://$DOMAIN/gitea/api/v1/orgs?access_token=$USER_TOKEN" \
  --data @- <<EOF
{
  "username": "foundry",
  "repo_admin_change_team_access": true
}
EOF

# Create repo
# for repo in $(find $DOCS_DIR -maxdepth 1 -mindepth 1 -type d -printf '%P\n'); do
curl_proxy "${CURL_OPTS[@]}" \
    --request POST "https://$DOMAIN/gitea/api/v1/orgs/foundry/repos?access_token=$USER_TOKEN" \
    --data @- <<EOF
{
  "name": "mkdocs",
  "private": false,
  "default_branch": "main"
}
EOF

git -C $MKDOCS_DIR init
git -C $MKDOCS_DIR add -A
git -C $MKDOCS_DIR commit -m "Initial commit" || true
git -C $MKDOCS_DIR push -u https://administrator:$ADMIN_PASS@$DOMAIN/gitea/foundry/mkdocs.git --all
