alloy-api:
  image: 
    repository: cmusei/alloy-api
    tag: '3.4.0'
    pullPolicy: Always
  command: ["bash", "-c", "update-ca-certificates && dotnet Alloy.Api.dll"]

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: $INGRESS_CLASS
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: $DOMAIN
        paths:
          - path:  /alloy/(hubs|api|swagger)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
          - $DOMAIN
  
  # If this deployment needs to trust non-public certificates,
  # create a configMap with the needed certifcates and specify
  # the configMap name here
  certificateMap: "appliance-root-ca"
  
  env:
    PathBase: "/alloy"
    CorsPolicy__Origins__0: https://$DOMAIN
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true
    Logging__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"
    # Connection String to database
    ConnectionStrings__PostgreSQL: "Server=$POSTGRES_SERVER;Port=5432;Database=alloy_db;Username=$POSTGRES_USER;Password='$POSTGRES_PASS';SSL Mode=Prefer;Trust Server Certificate=true;"

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORITY_URL
    Authorization__AuthorizationUrl: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORIZATION_URL
    Authorization__TokenUrl: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_TOKEN_URL
    Authorization__AuthorizationScope: 'player-api alloy-api caster-api steamfitter-api vm-api'
    Authorization__ClientId: "${OAUTH_ENV_NAME}_${OAUTH_GROUP_ID}_alloy-api"
    Authorization__ClientName: 'Alloy API'

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://$DOMAIN/$OAUTH_PROVIDER/realms/baby-yoda
    ResourceOwnerAuthorization__ClientId: "${OAUTH_ENV_NAME}_${OAUTH_GROUP_ID}_alloy-admin"
    #ResourceOwnerAuthorization__ClientSecret: ""
    ResourceOwnerAuthorization__UserName: crucible-admin@$DOMAIN # TODO
    ResourceOwnerAuthorization__Password: $CRUCIBLE_ADMIN_PASS # TODO
    ResourceOwnerAuthorization__Scope: 'openid profile alloy-api player-api caster-api steamfitter-api vm-api'

    # Crucible Application URLs
    ClientSettings__urls__playerApi: https://$DOMAIN/player/api
    ClientSettings__urls__casterApi: https://$DOMAIN/caster/api
    ClientSettings__urls__steamfitterApi: https://$DOMAIN/steamfitter/api

alloy-ui:
  image:
    repository: cmusei/alloy-ui
    pullPolicy: IfNotPresent
    tag: '3.2.6'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: $INGRESS_CLASS
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: "/alloy(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
          - $DOMAIN

  env: 
    ## basehref is path to the app
    APP_BASEHREF: "/alloy"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  # NOTE:  PlayerUIAddress is the URL to the Crucible - Player application
  settings: |-
    {
      "ApiUrl": "https://$DOMAIN/alloy",
      "OIDCSettings": {
        "authority": "https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORITY_URL",
        "client_id": "${OAUTH_ENV_NAME}_${OAUTH_GROUP_ID}_alloy-ui",
        "redirect_uri": "https://$DOMAIN/alloy/auth-callback",
        "post_logout_redirect_uri": "https://$DOMAIN/alloy",
        "response_type": "code",
        "scope": "openid profile alloy-api player-api caster-api steamfitter-api vm-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://$DOMAIN/alloy/auth-callback-silent"
      },
      "AppTitle": "Alloy",
      "AppTopBarText": "Alloy",
      "AppTopBarHexColor": "#719F94",
      "AppTopBarHexTextColor": "#FFFFFF",
      "PlayerUIAddress": "https://${DOMAIN}/player",
      "PollingIntervalMS": "3500",
      "UseLocalAuthStorage": true
    }
