apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
type: Opaque
stringData:
  initialRootPassword: $ADMIN_PASS
  databasePassword: $POSTGRES_PASS
  minio: foundry
  backup: foundry
  provider: "{ 
    name: 'openid_connect',
    label: '$OAUTH_PROVIDER',
      args: {
        name: '$OAUTH_PROVIDER',
        scope: ['openid','profile','email'],
        response_type: 'code',
        issuer: 'https://$DOMAIN/$OAUTH_PROVIDER',
        discovery: true,
        client_options: {
          identifier: 'gitlab',
          secret: '337bdcb1a23143a9b5a6aaa33c0e87d7',
          port: '443',
          scheme: 'https',
          host: '$DOMAIN/$OAUTH_PROVIDER',
          redirect_uri: 'https://$GITLAB_URL/users/auth/$OAUTH_PROVIDER/callback',
          end_session_endpoint: 'https://$DOMAIN/$OAUTH_PROVIDER/connect/endsession'
        }
      }
    }"
