#!/bin/bash
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.
#
# Import crucible example content into the appliance
#
# import-content
exports_path="seed/crucible"
domain=${domain-$DOMAIN}
directory=$(dirname "$BASH_SOURCE[0]")
cd $directory
source ../scripts/utils
replace foundry.local $domain $directory/$exports_path
replace crucible.io $domain $directory/$exports_path

helm delete alloy || true && sleep 5
helm delete caster || true && sleep 5
helm delete player || true && sleep 5
helm delete steamfitter || true && sleep 5

echo "sleeping for 20 seconds"
sleep 20
echo "forwarding port" 
kubectl port-forward service/postgresql 5432:5432 > /dev/null 2>&1 &
pid=$!

trap '{
  echo killing $pid
  kill $pid
}' EXIT
while ! nc -vz localhost 5432 > /dev/null 2>&1 ; do
  echo "waiting for port to become available "
  sleep 1
done

files=$(find $exports_path -type f -iname "*.sql" | sed "s/.*\///; s/\.sql//")
for file in $files; do
  PGPASSWORD=$POSTGRES_PASS dropdb -h localhost -U $POSTGRES_USER ${file}
  PGPASSWORD=$POSTGRES_PASS createdb -h localhost -U $POSTGRES_USER -T template0 ${file}
  PGPASSWORD=$POSTGRES_PASS psql -h localhost -U $POSTGRES_USER < $exports_path/${file}.sql
done

helm upgrade --install -f player.values.yaml player ../charts/player && sleep 5
helm upgrade --install -f caster.values.yaml caster ../charts/caster && sleep 5
helm upgrade --install -f steamfitter.values.yaml steamfitter ../charts/steamfitter && sleep 5
helm upgrade --install -f alloy.values.yaml alloy ../charts/alloy && sleep 5
