image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 6.0.0-debian-11-r0
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

auth:
  enabled: true
  rootUser: mongo
  rootPassword: "$ADMIN_PASS"
  usernames:
    - $STACKSTORM_MONGO_USER
  passwords:
    - $STACKSTORM_MONGO_PASS
  databases:
    - st2
  
service:
  nameOverride: "mongodb"
  type: ClusterIP
  port: 27017
  portName: mongodb

persistence:
  enabled: true
  storageClass: "$STORAGE_CLASS"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
  mountPath: /bitnami/mongodb
  