#!/bin/bash -x
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

#############################
#   Crucible Stack Install   #
#############################

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"
./setup-gitlab
# # Crucible Stack install
if [[ $IMPORT_CONTENT = false ]]; then 
  helm upgrade --install -f player.values.yaml player ../charts/player 
  helm upgrade --install -f caster.values.yaml caster ../charts/caster
  helm upgrade --install -f steamfitter.values.yaml steamfitter ../charts/steamfitter
  helm upgrade --install -f alloy.values.yaml alloy ../charts/alloy
  helm upgrade --install --wait -f mongodb.values.yaml mongodb bitnami/mongodb
  helm upgrade --install -f stackstorm-min.values.yaml stackstorm stackstorm/stackstorm-ha
fi

