#!/bin/bash -e
# 
# Copyright 2021 Carnegie Mellon University.
# Released under a BSD (SEI)-style license, please see LICENSE.md in the
# project root or contact permission@sei.cmu.edu for full terms.

#############################
#   Crucible Stack Install   #
#############################

# Change to the current directory
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../scripts/utils
import_vars ../env
helm repo add stackstorm https://helm.stackstorm.com/
#./setup-gitlab
# # Crucible Stack install
if [[ ${IMPORT_CONTENT-$IMPORT_CONTENT} = false ]]; then 
  helm_deploy -r ../env -p ../helm -u -v 1.4.1 -f player.values.yaml sei/player
  helm_deploy -r ../env -p ../helm -u -v 1.4.1 -f caster.values.yaml sei/caster
  helm_deploy -r ../env -p ../helm -u -v 1.4.0 -f alloy.values.yaml sei/alloy

  # get MOID for steamfitter
  echo "Attempting to get vsphere cluster"
  MOID=$(pwsh -c 'Connect-VIServer -server $env:VSPHERE_SERVER -user $env:VSPHERE_USER -password $env:VSPHERE_PASS | Out-Null; Get-Cluster -Name $env:VSPHERE_CLUSTER | select id')
  MOID=$(echo "${MOID}" | rev | cut -d '-' -f1 -f2 | rev)
  if [[ -n ${MOID} ]]; then
    sed -i "s/ VmTaskProcessing__ApiParameters__clusters:.*/ VmTaskProcessing__ApiParameters__clusters: ${MOID}/" "steamfitter.values.yaml"
    echo "vsphere cluster set"
  fi

  helm_deploy -r ../env -p ../helm -u -v 1.4.0 -f steamfitter.values.yaml sei/steamfitter
  helm_deploy -r ../env -p ../helm -u -f mongodb.values.yaml bitnami/mongodb
  helm_deploy -r ../env -p ../helm -u -v 0.80.0 --wait --timeout 10m -f stackstorm-min.values.yaml stackstorm/stackstorm-ha
fi