steamfitter-api:
  image:
    repository: cmusei/steamfitter-api
    tag: '3.6.1'
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: $INGRESS_CLASS
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: /steamfitter/(api|swagger|hubs)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - $DOMAIN
  certificateMap: "appliance-root-ca"

  
  env:
    PathBase: "/steamfitter"
    # Connection String to database
    ConnectionStrings__PostgreSQL: "Server=$POSTGRES_SERVER;Port=5432;Database=steamfitter_db;Username=$POSTGRES_USER;Password=$POSTGRES_PASS;SSL Mode=Prefer;Trust Server Certificate=true;"

    CorsPolicy__Origins__0: https://$DOMAIN
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true
    Logging__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"
    # OAuth2 Identity Client for Application
    Authorization__Authority: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORITY_URL
    Authorization__AuthorizationUrl: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORIZATION_URL
    Authorization__TokenUrl: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_TOKEN_URL
    Authorization__AuthorizationScope: "steamfitter-api vm-api"
    Authorization__ClientId: ${OAUTH_ENV_NAME}_${OAUTH_GROUP_ID}_steamfitter-api
    Authorization__ClientName: "Steamfitter API"

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORITY_URL
    ResourceOwnerAuthorization__ClientId: ${OAUTH_ENV_NAME}_${OAUTH_GROUP_ID}_steamfitter-admin
    ResourceOwnerAuthorization__UserName: crucible-admin@$DOMAIN #TODO
    ResourceOwnerAuthorization__Password: $CRUCIBLE_ADMIN_PASS #TODO
    ResourceOwnerAuthorization__Scope: "vm-api"

    ClientSettings__urls__steamfitterApi: https://$DOMAIN/steamfitter
    ClientSettings__urls__vmApi: https://$DOMAIN/vm

    # Stackstorm Configuration
    # TODO - Document Stackstorm dependencies
    VmTaskProcessing__ApiType: st2
    VmTaskProcessing__ApiUsername: "administrator"
    VmTaskProcessing__ApiPassword: "$ADMIN_PASS"
    VmTaskProcessing__ApiBaseUrl: "https://$DOMAIN/stackstorm"
    VmTaskProcessing__ApiParameters__clusters: ""

    # Basic seed data to jumpstart deployement
    # TODO - Document Seed data
    SeedData__Users__0__id: "$OAUTH_ADMIN_GUID"
    SeedData__Users__0__name:  "administrator@$DOMAIN"
    SeedData__Users__1__id: "$OAUTH_CRUCIBLE_ADMIN_GUID"
    SeedData__Users__1__name:  "crucible-admin@$DOMAIN"
    

    SeedData__UserPermissions__0__UserId: "$OAUTH_ADMIN_GUID"
    SeedData__UserPermissions__0__PermissionId: "00000000-0000-0000-0000-000000000001"
    SeedData__UserPermissions__1__UserId: "$OAUTH_CRUCIBLE_ADMIN_GUID"
    SeedData__UserPermissions__1__PermissionId: "00000000-0000-0000-0000-000000000001"

steamfitter-ui:
  image:
    repository: cmusei/steamfitter-ui
    pullPolicy: IfNotPresent
    tag: "3.6.1"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: $INGRESS_CLASS
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: "/steamfitter(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
        - $DOMAIN
  
  env: 
    ## basehref is path to the app
    APP_BASEHREF: "/steamfitter"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client
  settings: |- 
    {
      "ApiUrl": "https://$DOMAIN/steamfitter",
      "VmApiUrl": "https://$DOMAIN/vm",
      "ApiPlayerUrl": "https://$DOMAIN/player",
      "OIDCSettings": {
          "authority": "https://$DOMAIN/$OAUTH_PROVIDER/$OAUTH_AUTHORITY_URL",
          "client_id": "steamfitter-ui",
          "redirect_uri": "https://$DOMAIN/steamfitter/auth-callback",
          "post_logout_redirect_uri": "https://$DOMAIN/steamfitter",
          "response_type": "code",
          "scope": "openid profile steamfitter-api vm-api player-api",
          "automaticSilentRenew": true,
          "silent_redirect_uri": "https://$DOMAIN/steamfitter/auth-callback-silent"
      },
      "AppTitle": "Steamfitter",
      "AppTopBarHexColor": "#EF3A47",
      "AppTopBarHexTextColor": "#FFFFFF",
      "UseLocalAuthStorage": true
    }